[package]
name = "bytebit/statistics"
description = "A simple script to implement statistical functions not provided by the Lua standard API, developed especially for use on Roblox"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
testez = "roblox/testez@0.4.1"