name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install python dependencies
        run: pip3 install -r requirements.txt
      - name: get wally version
        id: get_wally_version
        run: echo "::set-output name=version-string::$(python3 ./scripts/get_wally_version_string.py)"
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: install wally packages
        run: wally install
      - name: run rojo build
        run: rojo build -o ./statistics-${{ steps.get_wally_version.outputs.version-string }}.rbxmx ./standalone-model.project.json
      - name: create-release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_wally_version.outputs.version-string }}
          tag_name: ${{ steps.get_wally_version.outputs.version-string }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload rbxmx file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./statistics-${{ steps.get_wally_version.outputs.version-string }}.rbxmx
          asset_name: statistics-${{ steps.get_wally_version.outputs.version-string }}.rbxmx
          asset_content_type: form
      - name: upload rbxmx file to Roblox
        run: |
          cd ./scripts
          python upload_model.py -a ${{ secrets.ASSET_ID }} -f ../statistics-${{ steps.get_wally_version.outputs.version-string }}.rbxmx -r "${{ secrets.UPLOADER_BOT_ROBLOSECURITY }}"
          cd ..
      - name: prepare wally package contents
        run: |
          mkdir -p ~/temp/statistics
          cp -r ./{Packages,src} ~/temp/statistics/
          cp ./{CHANGELOG.md,LICENSE,README.md,wally.lock,wally.toml} ~/temp/statistics/
          cp ./standalone-model.project.json ~/temp/statistics/default.project.json
      - name: prepare wally auth
        run: |
          mkdir ~/.wally
          echo -e '${{ secrets.WALLY_AUTH }}' > ~/.wally/auth.toml
      - name: publish wally package
        run: wally publish --project-path ~/temp/statistics/
